#!/usr/bin/env python3
"""Export the trained model to a C header for the Teensy firmware.

Reads artifacts/model.npz and writes:
  firmware/model_weights.h   - architecture, normalisation stats, weights/biases
  firmware/parity_vectors.h  - sample inputs + float32 outputs, so the host
                               parity test can prove the C++ engine reproduces
                               the Python network exactly.

Run:  python3 scripts/export_c.py
"""

from __future__ import annotations

import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rocketnn import simulator as sim          # noqa: E402
from rocketnn.nn import MLP                      # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(HERE, "artifacts")
FW = os.path.join(HERE, "firmware")


def fmt_array(values, per_line=8):
    """Format a flat float list as C initialiser rows."""
    out, row = [], []
    for i, v in enumerate(values):
        row.append(f"{np.float32(v):.8e}f")
        if len(row) == per_line:
            out.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("    " + ", ".join(row) + ",")
    return "\n".join(out)


def main():
    net, d = MLP.load(os.path.join(ART, "model.npz"))
    mean = d["mean"].astype(np.float32)
    std = d["std"].astype(np.float32)
    sizes = net.sizes
    n_layers = len(net.W)
    max_units = max(sizes)

    lines = []
    lines.append("// Auto-generated by scripts/export_c.py - do not edit by hand.")
    lines.append("// Trained evasion policy + threat classifier for the Teensy 4.1.")
    lines.append("#ifndef ROCKET_MODEL_WEIGHTS_H")
    lines.append("#define ROCKET_MODEL_WEIGHTS_H")
    lines.append("")
    lines.append(f"#define RNN_NUM_LAYERS {n_layers}")
    lines.append(f"#define RNN_NUM_FEATURES {sizes[0]}")
    lines.append(f"#define RNN_NUM_OUTPUTS {sizes[-1]}")
    lines.append(f"#define RNN_MAX_UNITS {max_units}")
    lines.append("")
    lines.append("// Output layout: [0]=fin_pitch cmd, [1]=fin_yaw cmd, [2..5]=class logits")
    lines.append(f"#define RNN_OUT_FIN_PITCH 0")
    lines.append(f"#define RNN_OUT_FIN_YAW   1")
    lines.append(f"#define RNN_OUT_CLASS0    2")
    lines.append(f"#define RNN_NUM_CLASSES   {sim.N_CLASSES}")
    lines.append("")

    lines.append(f"static const int rnn_layer_in[RNN_NUM_LAYERS]  = {{"
                 f"{', '.join(str(sizes[i]) for i in range(n_layers))}}};")
    lines.append(f"static const int rnn_layer_out[RNN_NUM_LAYERS] = {{"
                 f"{', '.join(str(sizes[i+1]) for i in range(n_layers))}}};")
    lines.append("// ReLU on hidden layers, linear output (1 = ReLU, 0 = linear).")
    relu_flags = ["1"] * (n_layers - 1) + ["0"]
    lines.append(f"static const int rnn_layer_relu[RNN_NUM_LAYERS] = {{{', '.join(relu_flags)}}};")
    lines.append("")

    lines.append("// Input standardisation: x_norm = (x - mean) / std")
    lines.append(f"static const float rnn_in_mean[RNN_NUM_FEATURES] = {{")
    lines.append(fmt_array(mean))
    lines.append("};")
    lines.append(f"static const float rnn_in_std[RNN_NUM_FEATURES] = {{")
    lines.append(fmt_array(std))
    lines.append("};")
    lines.append("")

    total_w = 0
    for i in range(n_layers):
        W = net.W[i].astype(np.float32).reshape(-1)   # row-major (out, in)
        b = net.b[i].astype(np.float32)
        total_w += W.size + b.size
        lines.append(f"// Layer {i}: {sizes[i]} -> {sizes[i+1]}  (row-major [out][in])")
        lines.append(f"static const float rnn_W{i}[{W.size}] = {{")
        lines.append(fmt_array(W))
        lines.append("};")
        lines.append(f"static const float rnn_b{i}[{b.size}] = {{")
        lines.append(fmt_array(b))
        lines.append("};")
        lines.append("")

    lines.append("static const float* const rnn_W[RNN_NUM_LAYERS] = {"
                 + ", ".join(f"rnn_W{i}" for i in range(n_layers)) + "};")
    lines.append("static const float* const rnn_b[RNN_NUM_LAYERS] = {"
                 + ", ".join(f"rnn_b{i}" for i in range(n_layers)) + "};")
    lines.append("")
    lines.append(f"// Total trainable parameters: {total_w}")
    lines.append("#endif  // ROCKET_MODEL_WEIGHTS_H")

    with open(os.path.join(FW, "model_weights.h"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote firmware/model_weights.h ({total_w} parameters, "
          f"{total_w*4} bytes as float32)")

    # ---- parity vectors: real in-distribution feature rows + f32 outputs ----
    rng = np.random.default_rng(7)
    feats = []
    for _ in range(30):
        scn = sim.sample_scenario(rng, kind=int(rng.integers(0, sim.N_CLASSES)))
        res = sim.run_engagement(scn, "expert", rng, record=True)
        if len(res["feats"]):
            feats.append(res["feats"][len(res["feats"]) // 2])
    feats = np.array(feats[:24], dtype=np.float32)

    outs = []
    for x in feats:
        xn = ((x - mean) / std).astype(np.float32)
        outs.append(net.forward_f32(xn))
    outs = np.array(outs, dtype=np.float32)

    p = []
    p.append("// Auto-generated by scripts/export_c.py - parity test fixtures.")
    p.append("// Raw (un-normalised) sensor feature rows and the float32 network")
    p.append("// outputs computed in Python. The C++ engine must reproduce these.")
    p.append("#ifndef ROCKET_PARITY_VECTORS_H")
    p.append("#define ROCKET_PARITY_VECTORS_H")
    p.append(f"#define RNN_PARITY_N {len(feats)}")
    p.append(f"static const float rnn_parity_in[RNN_PARITY_N][{feats.shape[1]}] = {{")
    for row in feats:
        p.append("    {" + ", ".join(f"{v:.8e}f" for v in row) + "},")
    p.append("};")
    p.append(f"static const float rnn_parity_out[RNN_PARITY_N][{outs.shape[1]}] = {{")
    for row in outs:
        p.append("    {" + ", ".join(f"{v:.8e}f" for v in row) + "},")
    p.append("};")
    p.append("#endif  // ROCKET_PARITY_VECTORS_H")
    with open(os.path.join(FW, "parity_vectors.h"), "w") as f:
        f.write("\n".join(p) + "\n")
    print(f"wrote firmware/parity_vectors.h ({len(feats)} vectors)")


if __name__ == "__main__":
    main()
