#!/usr/bin/env python3
"""Export the trained stabilization model to C headers for the Teensy.

Reads artifacts/stab_model.npz and writes:
  firmware/stab_model_weights.h   - arch, normalisation, weights (snn_ prefix,
                                    so it coexists with the evasion net)
  firmware/stab_parity_vectors.h  - fixtures proving C++ == Python

Run:  python3 scripts/export_stab_c.py
"""

from __future__ import annotations

import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rocketnn import stab_sim as sim    # noqa: E402
from rocketnn.nn import MLP             # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(HERE, "artifacts")
FW = os.path.join(HERE, "firmware")


def fmt_array(values, per_line=8):
    out, row = [], []
    for v in values:
        row.append(f"{np.float32(v):.8e}f")
        if len(row) == per_line:
            out.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("    " + ", ".join(row) + ",")
    return "\n".join(out)


def main():
    net, d = MLP.load(os.path.join(ART, "stab_model.npz"))
    mean = d["mean"].astype(np.float32)
    std = d["std"].astype(np.float32)
    sizes = net.sizes
    n_layers = len(net.W)

    lines = []
    lines.append("// Auto-generated by scripts/export_stab_c.py — do not edit by hand.")
    lines.append("// Trained fin-stabilization policy for the Teensy 4.1.")
    lines.append("// Trained on real F-class thrust curves (thrustcurve.org data).")
    lines.append("#ifndef ROCKET_STAB_MODEL_WEIGHTS_H")
    lines.append("#define ROCKET_STAB_MODEL_WEIGHTS_H")
    lines.append("")
    lines.append(f"#define SNN_NUM_LAYERS {n_layers}")
    lines.append(f"#define SNN_NUM_FEATURES {sizes[0]}")
    lines.append(f"#define SNN_NUM_OUTPUTS {sizes[-1]}")
    lines.append(f"#define SNN_MAX_UNITS {max(sizes)}")
    lines.append("")
    lines.append("// Output layout: [0]=fin_pitch cmd, [1]=fin_yaw cmd, both in [-1,1]")
    lines.append("")
    lines.append(f"static const int snn_layer_in[SNN_NUM_LAYERS]  = {{"
                 f"{', '.join(str(sizes[i]) for i in range(n_layers))}}};")
    lines.append(f"static const int snn_layer_out[SNN_NUM_LAYERS] = {{"
                 f"{', '.join(str(sizes[i+1]) for i in range(n_layers))}}};")
    relu_flags = ["1"] * (n_layers - 1) + ["0"]
    lines.append(f"static const int snn_layer_relu[SNN_NUM_LAYERS] = {{{', '.join(relu_flags)}}};")
    lines.append("")
    lines.append("// Input standardisation: x_norm = (x - mean) / std")
    lines.append("static const float snn_in_mean[SNN_NUM_FEATURES] = {")
    lines.append(fmt_array(mean))
    lines.append("};")
    lines.append("static const float snn_in_std[SNN_NUM_FEATURES] = {")
    lines.append(fmt_array(std))
    lines.append("};")
    lines.append("")

    total = 0
    for i in range(n_layers):
        W = net.W[i].astype(np.float32).reshape(-1)
        b = net.b[i].astype(np.float32)
        total += W.size + b.size
        lines.append(f"// Layer {i}: {sizes[i]} -> {sizes[i+1]}  (row-major [out][in])")
        lines.append(f"static const float snn_W{i}[{W.size}] = {{")
        lines.append(fmt_array(W))
        lines.append("};")
        lines.append(f"static const float snn_b{i}[{b.size}] = {{")
        lines.append(fmt_array(b))
        lines.append("};")
        lines.append("")

    lines.append("static const float* const snn_W[SNN_NUM_LAYERS] = {"
                 + ", ".join(f"snn_W{i}" for i in range(n_layers)) + "};")
    lines.append("static const float* const snn_b[SNN_NUM_LAYERS] = {"
                 + ", ".join(f"snn_b{i}" for i in range(n_layers)) + "};")
    lines.append("")
    lines.append(f"// Total trainable parameters: {total}")
    lines.append("#endif  // ROCKET_STAB_MODEL_WEIGHTS_H")
    with open(os.path.join(FW, "stab_model_weights.h"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote firmware/stab_model_weights.h ({total} parameters, {total*4} bytes)")

    # ---- parity vectors: real in-distribution feature rows ------------------
    rng = np.random.default_rng(11)

    def pol(x):
        xn = (x - mean) / std
        return np.clip(net.forward(xn[None, :])[0], -1, 1)

    feats = []
    for _ in range(12):
        r = sim.fly(sim.sample_flight(rng), pol, record=True)
        if len(r["feats"]) >= 2:
            feats.append(r["feats"][len(r["feats"]) // 3])
            feats.append(r["feats"][2 * len(r["feats"]) // 3])
    feats = np.array(feats[:20], dtype=np.float32)

    outs = []
    for x in feats:
        xn = ((x - mean) / std).astype(np.float32)
        outs.append(net.forward_f32(xn))
    outs = np.array(outs, dtype=np.float32)

    p = []
    p.append("// Auto-generated by scripts/export_stab_c.py — parity fixtures.")
    p.append("#ifndef ROCKET_STAB_PARITY_VECTORS_H")
    p.append("#define ROCKET_STAB_PARITY_VECTORS_H")
    p.append(f"#define SNN_PARITY_N {len(feats)}")
    p.append(f"static const float snn_parity_in[SNN_PARITY_N][{feats.shape[1]}] = {{")
    for row in feats:
        p.append("    {" + ", ".join(f"{v:.8e}f" for v in row) + "},")
    p.append("};")
    p.append(f"static const float snn_parity_out[SNN_PARITY_N][{outs.shape[1]}] = {{")
    for row in outs:
        p.append("    {" + ", ".join(f"{v:.8e}f" for v in row) + "},")
    p.append("};")
    p.append("#endif  // ROCKET_STAB_PARITY_VECTORS_H")
    with open(os.path.join(FW, "stab_parity_vectors.h"), "w") as f:
        f.write("\n".join(p) + "\n")
    print(f"wrote firmware/stab_parity_vectors.h ({len(feats)} vectors)")


if __name__ == "__main__":
    main()
